# general configuration
url: afrouzi.github.io
baseurl: ''

# compass configuration
compass:
  # an avatar or logo (optional)
  title: "Hassan Afrouzi"
  description: "Hassan Afrouzi is an Assitant Professor of Economics at Columbia University and Faculty Research Fellow at the National Bureau of Economic Research (NBER). My research focuses on macroeconomic implications of imperfect information and imperfect competition. I am currently a Visiting Scholar at the Becker-Friedman Institute at the University of Chicago."
  author: "Hassan Afrouzi"
  logo: "/images/afrouzi_2.jpg"
  # author will appear under the avatar (optional)
  # tagline will appear under the title (optional)
  tagline: "
  Columbia University <br/>
  Department of Economics <br/>
  420 W. 118th St, 1105A IAB<br/>
  New York, NY 10027<br/>
  <span class='fa fa-paper-plane'></span> <a href='mailto:ha2475@columbia.edu'>ha2475@columbia.edu</a>
  "
  links: "
  <strong>Links:</strong> </br>
  <span class='fa fa-brain'></span>
  <a href='http://cognition.econ.columbia.edu'>Cognition & Decision Lab</a> </br>

  <span class='fa fa-github'></span>
  <a href='https://afrouzi.com/DRIPs.jl/dev'>DRIPs</a> </br> 

  <span class='fa fa-google'></span>
  <a href='https://scholar.google.com/citations?user=mnxLP9YAAAAJ&hl=en'>Google Scholar</a> </br></br>
  "

  keywords: "
  Hassan Afrouzi, Assistant Professor, Economics, Columbia University, NBER, National Bureau of Economic Research, macroeconomics, monetary economics, imperfect information, imperfect competition, Visiting Scholar, Becker-Friedman Institute at the University of Chicago
  "
  
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: true
  # Twitter @username (as defined by the Twitter Card specs)
  twitter: "hafrouzi"

# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

plugins:
  - jekyll-redirect-from

collections:
  files:
    output: true
    permalink: /:path/