# general configuration
url: http://www.afrouzi.com 
baseurl: ''

# compass configuration
compass:
  # an avatar or logo (optional)
  author: "Hassan Afrouzi"
  logo: "/images/afrouzi.jpg"
  # author will appear under the avatar (optional)
  # tagline will appear under the title (optional)
  tagline: "
  <strong>Current Affiliations:</strong> </br>
  Assistant Professor, Columbia </br>
  Research Network Affiliate, CESifo</br></br>
  <strong>Links:</strong> </br>
  <a href='http://cognition.econ.columbia.edu'>Cognition and Decision Lab</a> </br>
  <a href='http://github.com/afrouzi/DRIPs.jl'>DRIPs</a> </br> 
  <a href='http://afrouzi.com/cv.pdf'>Curriculum Vitae</a> </br>
  <a href='https://scholar.google.com/citations?user=mnxLP9YAAAAJ&hl=en'>Google Scholar</a> </br></br>
  <strong>Contact:</strong> </br>
  <a href='mailto:ha2475@columbia.edu'>ha2475@columbia.edu</a> </br>
  "
  
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: true
  # Twitter @username (as defined by the Twitter Card specs)
  twitter: "hafrouzi"

# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
