# general configuration
url: https://afrouzi.com
baseurl: ''
title: "Hassan Afrouzi"

# compass configuration
compass:
  # an avatar or logo (optional)
  title: "Hassan Afrouzi | Associate Professor (without tenure) | Columbia Economics"
  description: "Hassan Afrouzi is an Associate Professor of Economics (without tenure) at Columbia University and a Faculty Research Fellow at the National Bureau of Economic Research (NBER). His research focuses on the macroeconomic implications of imperfect information and imperfect competition."
  author: "Hassan Afrouzi"
  logo: "/images/afrouzi_2.jpg"
  email: "hassan@afrouzi.com"

  keywords: "
  Hassan Afrouzi, Associate, Economics, Columbia University, NBER, National Bureau of Economic Research, macroeconomics, monetary economics, imperfect information, imperfect competition, Visiting Scholar, Becker-Friedman Institute at the University of Chicago
  "

  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: true

# exclude
exclude: ["CNAME", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]

# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

plugins:
  - jekyll-redirect-from

collections:
  files:
    output: true
    permalink: /:path/

# Adobe PDF Embed API (Document Cloud View SDK)
# Get a free client ID from https://developer.adobe.com/document-services/apis/pdf-embed/
# Leave blank to fall back to iframe embedding.
adobe_pdf_client_id: "b22a7fc3bda64abaa1006c39b17afe5c"
# adobe_pdf_client_id: "4db393aa0b3b4d87a3db545398d565d8"  # local override